name: Kevin Connell, Technology Leader
description:  Kevin Connell's Blog
url:  http://www.kevinjconnell.com/blog
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-feed
feed:
  path: feed.xml
